WaC/WaC/Models/Base.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaC.Models
{
    public class Base
    {
        public int Id { get; set; }
    }
}

WaC/WaC/Models/Character.cs
using WaC.Interfaces;

namespace WaC.Models
{
    public class Character : ICharListItemVm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int MovieId { get; set; }
    }
}

WaC/WaC/Models/ErrorViewModel.cs
using System;

namespace WaC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WaC/WaC/Models/Movie.cs
using System.Collections.Generic;
using WaC.Interfaces;

namespace WaC.Models
{
    public class Movie : IMovieListItemVm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int ReleasedYear { get; set; }
        public List<Character> Characters { get; set; }
    }
}

WaC/WaC/ViewModels/BaseListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaC.Interfaces;

namespace WaC.ViewModels
{
    public class BaseListVM : IBaseListItemVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public string ShortDescription { get; set; }
    }
}

WaC/WaC/ViewModels/CharacterListItemVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WaC.Models;
using WaC.Interfaces;

namespace WaC.ViewModels
{
    public class CharacterListItemVM: BaseListVM
    {
        public string MovieName { get; set; }
    }
}

WaC/WaC/ViewModels/CharacterListVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WaC.ViewModels
{
    public class CharacterListVM
    {
        public List<BaseListVM> CharactersList { get; set; }
        //public string MovieName { get; set; }
    }
}

WaC/WaC/Controllers/CharacterController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WaC.Interfaces;
using WaC.Models;
using WaC.ViewModels;

namespace WaC.Controllers
{
    public class CharacterController : Controller
    {
        private readonly IMockRepository<ICharListItemVm> _characterMockRepository;
        private readonly IConvertService<ICharListItemVm> _convertToVM;
        public List<BaseListVM> charactersListVM;

        public CharacterController(IMockRepository<ICharListItemVm> characterMockRepository, IConvertService<ICharListItemVm> convertToVM)
        {
            _characterMockRepository = characterMockRepository;
            _convertToVM = convertToVM;
        }

        // GetAll: Open List
        public ViewResult List()
        {
            var charList = _characterMockRepository.GetAll;
            charactersListVM = _convertToVM.EntityItemToListVM(charList);

            return View(charactersListVM);
        }

        // GetById: Open Details
        public ViewResult Details(int Id)
        {
            return View(_characterMockRepository.GetById(Id));
        }

        // Open Create Form
        public ViewResult Create()
        {
            return View();
        }

        // Create
        public ActionResult Add(Character character)
        {
            _characterMockRepository.Post(character);
            return RedirectToAction("List");
        }

        // Open Edit Form
        public ViewResult Edit(int Id)
        {
            return View(_characterMockRepository.GetById(Id));
        }

        // Update
        public ActionResult SubmitEdit(Character character)
        {
            _characterMockRepository.Put(character);
            return RedirectToAction("List");
        }


        // Delete
        public ActionResult Delete(int Id)
        {
            _characterMockRepository.Delete(Id);
            return RedirectToAction("List");
        }

    }
}

WaC/WaC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WaC.Models;

namespace WaC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WaC/WaC/Controllers/MovieController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WaC.Interfaces;
using WaC.Models;
using WaC.ViewModels;
using WaC.Tools.Services;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using WaC.MockDataRepos;

namespace WaC.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMockRepository<IMovieListItemVm> _moviesMockRepository;
        private readonly IConvertService<IMovieListItemVm> _convertToVM;
        public List<BaseListVM> moviesListVM;

        public MovieController(IMockRepository<IMovieListItemVm> characterMockRepository, IConvertService<IMovieListItemVm> convertToVM)
        {
            _moviesMockRepository = characterMockRepository;
            _convertToVM = convertToVM;
        }

        public ViewResult List()
        {
            moviesListVM = _convertToVM.EntityItemToListVM(_moviesMockRepository.GetAll);

            return View(moviesListVM);
        }

        public ViewResult Details(int Id)
        {
            return View();
        }

    }
}

WaC/WaC/Views/Character/Create.cshtml
@model WaC.Models.Character

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Character</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input style="display:none" asp-for="Id" value="0" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <input asp-for="MovieId" class="form-control" />
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WaC/WaC/Views/Character/Details.cshtml
@model WaC.Models.Character

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Character</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content(Model.ImageUrl)" style="width: 100px" alt="Alternate Text" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

WaC/WaC/Views/Character/Edit.cshtml
@model WaC.Models.Character

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Character</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SubmitEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input style="display:none" asp-for="Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <input asp-for="MovieId" class="form-control" />
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WaC/WaC/Views/Character/List.cshtml
@model IEnumerable<WaC.ViewModels.BaseListVM>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortDescription)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img src="@Url.Content(item.ImageUrl)" style="width: 100px" alt="Alternate Text" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShortDescription)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

WaC/WaC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WaC/WaC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WaC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WaC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="List">Characters</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WaC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>